[project]
name = "mcp-modal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
    "mcp[cli]>=1.6.0",
    "modal>=0.74.20",
    "pydantic>=2.11.3",
]
